# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
FROM node:lts-alpine AS builder
WORKDIR /app
# install dependencies
COPY package.json package-lock.json* yarn.lock* ./
RUN npm install --ignore-scripts
# copy source
COPY . .
# build
RUN npm run build

FROM node:lts-alpine AS runtime
WORKDIR /app
# Copy built app and production deps
COPY package.json package-lock.json* yarn.lock* ./
RUN npm install --production --ignore-scripts
COPY --from=builder /app/dist ./dist
# Ensure binary is executable
RUN chmod +x dist/index.js
# Set entrypoint
ENTRYPOINT ["node", "dist/index.js"]
